export interface RoadmapStepConfig {
  number: number;
  title: string;
  subtitle?: string;
  timeline: string;
  responsible: string;
  description: string;
  details?: string[];
  artifactName: string;
  formFields: FormFieldConfig[];
}

export interface FormFieldConfig {
  name: string;
  label: string;
  type: 'text' | 'textarea' | 'select' | 'multiselect' | 'checkbox' | 'date' | 'checklist';
  placeholder?: string;
  required?: boolean;
  options?: { value: string; label: string }[];
}

export const ROADMAP_STEPS: RoadmapStepConfig[] = [
  {
    number: 0,
    title: 'Приоритизация',
    subtitle: 'Определение сценариев и готовности к интеграции',
    timeline: '1–3 дня',
    responsible: 'Стрим лид / PO',
    description: 'Сформулируйте клиентские сценарии, проверьте наличие API, оцените сложность интеграции и примите решение о подключении.',
    details: [
      'Сформулировать 3-5 клиентских запросов/сценариев, которые пользователь может выразить текстом',
      'Определить, есть ли готовые API-ручки. Без них подключение невозможно',
      'Оценить частотность сценариев по данным поддержки / аналитики',
      'Выбрать 1-3 сценария для первого запуска (рекомендация: информационные, не мутирующие)',
      'Определить уровень сложности: простой (1 спринт), средний (1-2), сложный (2-3)',
      'Убедиться в возможности выделить 1 backend-разработчика на 1-2 спринта',
      'Принять решение и зафиксировать в бэклоге стрима',
    ],
    artifactName: 'Решение о подключении',
    formFields: [
      {
        name: 'scenarios',
        label: 'Клиентские сценарии (3-5 запросов)',
        type: 'textarea',
        required: true,
        placeholder: '1. «Покажи мои операции»\n2. «Какой статус платежа?»\n3. «Когда заканчивается депозит?»',
      },
      {
        name: 'selectedScenarios',
        label: 'Сценарии для первого запуска (1-3)',
        type: 'multiselect',
        required: true,
        options: [
          { value: 'tariffs', label: 'Тарифы и остатки' },
          { value: 'sbp_transfer', label: 'Перевод по СБП' },
          { value: 'invoicing', label: 'Выставление счетов' },
          { value: 'account_block', label: 'Блокировка счёта' },
          { value: 'company_profile', label: 'Профиль компании' },
          { value: 'transactions', label: 'История операций' },
          { value: 'deposit_info', label: 'Информация по депозиту' },
          { value: 'payment_status', label: 'Статус платежа' },
          { value: 'custom', label: 'Свой сценарий' },
        ],
      },
      {
        name: 'complexityLevel',
        label: 'Уровень сложности интеграции',
        type: 'select',
        required: true,
        options: [
          { value: 'simple', label: 'Простой — 1-2 API-ручки, инфо-запрос (1 спринт)' },
          { value: 'medium', label: 'Средний — 3-5 ручек, нужен контекст клиента (1-2 спринта)' },
          { value: 'complex', label: 'Сложный — 5+ ручек, агентская логика (2-3 спринта)' },
        ],
      },
      {
        name: 'apiReadiness',
        label: 'Готовность API',
        type: 'checklist',
        options: [
          { value: 'api_exists', label: 'API-ручки уже существуют' },
          { value: 'api_documented', label: 'API задокументировано (OpenAPI / Confluence)' },
          { value: 'api_tested', label: 'API протестировано и работает стабильно' },
          { value: 'developer_available', label: 'Backend-разработчик (Java/Python) выделен на 1-2 спринта' },
          { value: 'decision_made', label: 'Решение о подключении принято и зафиксировано в бэклоге' },
        ],
      },
    ],
  },
  {
    number: 1,
    title: 'Подготовка',
    subtitle: 'Карточка навыка, отправка и назначение исполнителя',
    timeline: '1–2 дня',
    responsible: 'PO + Системный аналитик',
    description: 'Заполните карточку навыка по шаблону, отправьте на согласование, назначьте backend-разработчика.',
    details: [
      '1.1. Заполнить карточку навыка: название, команда, PO, Tech Lead, таблица сценариев (фраза клиента / API-ручка / параметры / ответ)',
      '1.2. Для каждого сценария указать необходимые данные клиента (userId, accountId и т.д.)',
      '1.3. Отправить карточку на spotlight-platform@alfaintra.net с темой «[Подключение к Spotlight] — <Продукт>»',
      '1.4. Дождаться ответа (до 1 рабочего дня): согласование, репозиторий в MCPHUB, инструкция по доступам',
      '1.5. Зафиксировать контактное лицо из команды Spotlight',
      '1.6. Назначить backend-разработчика и передать ему инструкцию + карточку навыка',
    ],
    artifactName: 'Карточка навыка',
    formFields: [
      { name: 'productName', label: 'Название продукта', type: 'text', required: true, placeholder: 'Тарифы и остатки' },
      { name: 'teamName', label: 'Название команды', type: 'text', required: true },
      { name: 'poName', label: 'PO (имя)', type: 'text', required: true },
      { name: 'poEmail', label: 'PO (email)', type: 'text', required: true, placeholder: 'po@alfaintra.net' },
      { name: 'techLeadName', label: 'Tech Lead (имя)', type: 'text', required: true },
      { name: 'techLeadEmail', label: 'Tech Lead (email)', type: 'text', required: true, placeholder: 'lead@alfaintra.net' },
      {
        name: 'scenariosTable',
        label: 'Таблица сценариев (фраза клиента → API-ручка → параметры → ответ)',
        type: 'textarea',
        required: true,
        placeholder: '«Какой у меня тариф?» → GET /api/tariffs → userId → {name, price, nextPayment}\n«Сколько на счёте?» → GET /api/accounts/:id/balance → accountId → {balance, currency}',
      },
      {
        name: 'clientDataFields',
        label: 'Необходимые данные клиента для сценариев',
        type: 'textarea',
        placeholder: 'userId — идентификатор пользователя\naccountId — номер счёта\ncustomerId — идентификатор клиента',
      },
      { name: 'plannedLaunchDate', label: 'Плановая дата запуска', type: 'date' },
      {
        name: 'prepChecklist',
        label: 'Чек-лист подготовки',
        type: 'checklist',
        options: [
          { value: 'card_filled', label: 'Карточка навыка заполнена по шаблону' },
          { value: 'card_sent', label: 'Карточка отправлена на spotlight-platform@alfaintra.net' },
          { value: 'response_received', label: 'Ответ получен, сценарии согласованы' },
          { value: 'contact_fixed', label: 'Контактное лицо из команды Spotlight зафиксировано' },
          { value: 'developer_assigned', label: 'Backend-разработчик назначен' },
          { value: 'instructions_passed', label: 'Инструкция и карточка переданы разработчику' },
        ],
      },
    ],
  },
  {
    number: 2,
    title: 'Получение доступов',
    subtitle: 'Репозиторий, AI Flow, Keycloak, API-спецификация',
    timeline: '1–2 дня',
    responsible: 'Разработчик',
    description: 'Получите все необходимые доступы: репозиторий в MCPHUB, AI Flow, тестовый Keycloak, API-спецификация, ТУЗ.',
    details: [
      'Получить репозиторий в проекте MCPHUB (создаётся автоматически после согласования карточки)',
      'Подать заявку на доступ к AI Flow (конструктор сценариев) — 1-2 рабочих дня',
      'Создать тестовый client_id в Keycloak по инструкции — 1 рабочий день',
      'Убедиться, что есть доступ к API-спецификации целевой системы (OpenAPI / Confluence / PDF)',
      'Убедиться в наличии данных ТУЗ для доступа к целевой системе',
      'Согласовать ролевую модель с ДКБ (если не было сделано ранее)',
    ],
    artifactName: 'Заявка на доступы',
    formFields: [
      { name: 'developerName', label: 'ФИО разработчика', type: 'text', required: true },
      { name: 'developerEmail', label: 'Email разработчика', type: 'text', required: true },
      {
        name: 'accessChecklist',
        label: 'Чек-лист доступов',
        type: 'checklist',
        options: [
          { value: 'mcphub_repo', label: 'Репозиторий в MCPHUB получен' },
          { value: 'ai_flow_requested', label: 'Заявка на доступ к AI Flow подана' },
          { value: 'ai_flow_granted', label: 'Доступ к AI Flow получен' },
          { value: 'keycloak_client', label: 'Тестовый client_id в Keycloak создан' },
          { value: 'api_spec_access', label: 'Доступ к API-спецификации целевой системы есть' },
          { value: 'tuz_data', label: 'Данные ТУЗ для целевой системы есть' },
          { value: 'role_model', label: 'Ролевая модель согласована с ДКБ' },
        ],
      },
    ],
  },
  {
    number: 3,
    title: 'Разработка MCP-сервера',
    subtitle: 'Инициализация, реализация инструментов, безопасность, тесты',
    timeline: '1–2 спринта',
    responsible: 'Разработчик',
    description: 'Создайте MCP-сервер по шаблону, реализуйте инструменты для каждого сценария, обеспечьте безопасность и пройдите локальное тестирование.',
    details: [
      '3.1. Выбрать язык (Java Spring Boot / Python FastMCP), склонировать шаблон из MCPHUB',
      '3.2. Настроить проект: имя в kebab-case, протокол STATELESS, эндпоинт /mcp, транспорт streamable-http',
      '3.3. Для каждого сценария создать @Tool-метод: приём параметров → HTTP-вызов к API → фильтрация → JSON (до 4000 токенов)',
      '3.4. Для каждого инструмента — подробное описание на английском: что делает, что возвращает, когда использовать',
      '3.5. Реализовать проброс JWT-токена, логирование вызовов, обработку ошибок (без HTTP 500)',
      '3.6. Проверка безопасности: нет хардкод-токенов, нет секретов в description, ПДн маскируются',
      '3.7. Локальное тестирование: сборка, запуск, health check, tools/list, tools/call, edge-cases',
    ],
    artifactName: 'Конфигурация MCP-сервера',
    formFields: [
      {
        name: 'template',
        label: 'Шаблон MCP-сервера',
        type: 'select',
        required: true,
        options: [
          { value: 'java', label: 'Java (Spring Boot)' },
          { value: 'python', label: 'Python (FastMCP)' },
        ],
      },
      { name: 'serviceName', label: 'Название сервиса (kebab-case)', type: 'text', required: true, placeholder: 'tariffs-info-mcp-server' },
      { name: 'targetApiUrl', label: 'URL целевого API', type: 'text', required: true, placeholder: 'https://api.internal/v1/...' },
      { name: 'port', label: 'Порт actuator', type: 'text', placeholder: '8081' },
      {
        name: 'tools',
        label: 'Список инструментов (@Tool)',
        type: 'textarea',
        required: true,
        placeholder: 'get_tariff — Get current tariff for a user\nget_balance — Get account balance by accountId\nget_payment_status — Check payment status',
      },
      {
        name: 'toolDescriptions',
        label: 'Описания инструментов (на английском)',
        type: 'textarea',
        placeholder: 'get_tariff: Returns the current tariff name, monthly fee, and next billing date. Use when user asks about their tariff or pricing plan. Example queries: "What is my tariff?", "How much do I pay?"',
      },
      {
        name: 'devChecklist',
        label: 'Чек-лист разработки',
        type: 'checklist',
        options: [
          { value: 'repo_cloned', label: 'Шаблон склонирован из MCPHUB' },
          { value: 'project_configured', label: 'Имя, протокол STATELESS, эндпоинт /mcp, streamable-http настроены' },
          { value: 'tools_implemented', label: 'Все @Tool-методы реализованы' },
          { value: 'descriptions_written', label: 'Описания инструментов написаны на английском' },
          { value: 'jwt_passthrough', label: 'Проброс JWT-токена к целевому API реализован' },
          { value: 'logging_added', label: 'Логирование каждого вызова включено' },
          { value: 'error_handling', label: 'Обработка ошибок: корректный JSON, без HTTP 500' },
          { value: 'no_hardcoded_secrets', label: 'Нет хардкод-токенов и секретов в коде' },
          { value: 'pdn_masked', label: 'ПДн маскируются в ответах' },
          { value: 'build_ok', label: 'Проект собирается без ошибок' },
          { value: 'server_starts', label: 'Сервер запускается локально' },
          { value: 'health_ok', label: 'Health endpoint: {"status":"UP"}' },
          { value: 'initialize_ok', label: 'POST /mcp initialize проходит успешно' },
          { value: 'tools_list_ok', label: 'tools/list возвращает все инструменты' },
          { value: 'tools_call_ok', label: 'tools/call возвращает ожидаемые данные' },
          { value: 'error_inputs_tested', label: 'Ошибочные входные данные обработаны' },
          { value: 'api_unavailable_tested', label: 'Недоступность целевого API обработана' },
          { value: 'unit_tests_written', label: 'Юнит-тесты написаны' },
        ],
      },
    ],
  },
  {
    number: 4,
    title: 'Публикация MCP-сервера',
    subtitle: 'Описание примитивов, Code review, AppSec, деплой',
    timeline: '2–3 дня',
    responsible: 'Разработчик',
    description: 'Подготовьте описание примитивов, пройдите code review и AppSec, закажите сетевые доступы и деплой.',
    details: [
      '4.1. Заполнить шаблон описания примитивов (Tools, Resources, Prompts) и отправить на mcphub_support@alfaintra.net',
      '4.2. Подать код на ревью (Васин Артем Г., Давидович Михаил Б.): транспорт, эндпоинт, описания, логирование, безопасность',
      '4.3. Пройти стандартный AppSec-апрув',
      '4.4. При необходимости — заказать сетевые доступы (Луцюк Павел Александрович)',
      '4.5. Создать задачу Jira с меткой MCPHUB_DEPLOYMENT: среда, репозиторий, версия. Дождаться деплоя (до 3 дней)',
    ],
    artifactName: 'Заявка на деплой',
    formFields: [
      { name: 'jiraTicket', label: 'Номер тикета Jira (MCPHUB_DEPLOYMENT)', type: 'text', placeholder: 'MCPHUB-XXX' },
      { name: 'repoUrl', label: 'URL репозитория в MCPHUB', type: 'text', required: true },
      { name: 'version', label: 'Версия для деплоя', type: 'text', placeholder: '1.0.0' },
      { name: 'reviewNotes', label: 'Комментарии для ревью', type: 'textarea' },
      { name: 'mcpServerUrl', label: 'Полученный URL MCP-сервера после деплоя', type: 'text', placeholder: 'https://<host>/<service>/mcp' },
      {
        name: 'publishChecklist',
        label: 'Чек-лист публикации',
        type: 'checklist',
        options: [
          { value: 'primitives_sent', label: 'Описание примитивов отправлено на mcphub_support@alfaintra.net' },
          { value: 'code_review_submitted', label: 'Код подан на ревью' },
          { value: 'code_review_approved', label: 'Code review пройден (апрув получен)' },
          { value: 'appsec_approved', label: 'AppSec-апрув пройден' },
          { value: 'network_access', label: 'Сетевые доступы заказаны (если нужны)' },
          { value: 'jira_created', label: 'Задача Jira с MCPHUB_DEPLOYMENT создана' },
          { value: 'deployed_test', label: 'Задеплоен в test' },
          { value: 'deployed_prod', label: 'Задеплоен в prod' },
          { value: 'mcp_url_received', label: 'URL MCP-сервера получен' },
        ],
      },
    ],
  },
  {
    number: 5,
    title: 'Подключение к AI Flow и тестирование',
    subtitle: 'Настройка сценария, тестирование, подключение к Spotlight',
    timeline: '2–3 дня',
    responsible: 'Разработчик',
    description: 'Настройте сценарий в AI Flow, протестируйте все кейсы через встроенный чат, запросите подключение к маршрутизатору Spotlight.',
    details: [
      '5.1. Создать сценарий в AI Flow: компонент MCP Tool → URL сервера → streamable-http → маппинг параметров',
      '5.2. Убедиться, что AI Flow обнаружил инструменты через tools/list',
      '5.3. Тестирование: релевантный запрос → правильный инструмент; нерелевантный → не вызывается; невалидные данные → ошибка',
      '5.4. Проверить, что AI корректно формулирует ответ на естественном языке',
      '5.5. Уведомить команду Spotlight: «Навык готов, прошу подключить к Spotlight»',
      '5.6. Дождаться добавления навыка в маршрутизатор (1-2 рабочих дня)',
    ],
    artifactName: 'Конфигурация сценария AI Flow',
    formFields: [
      { name: 'scenarioName', label: 'Название сценария в AI Flow', type: 'text', required: true },
      { name: 'mcpServerUrl', label: 'URL MCP-сервера', type: 'text', required: true, placeholder: 'https://<host>/<service>/mcp' },
      {
        name: 'triggerPhrases',
        label: 'Триггерные фразы (примеры клиентских запросов)',
        type: 'textarea',
        required: true,
        placeholder: 'Какой у меня тариф?\nСколько на счёте?\nПокажи остаток на расчётном счёте',
      },
      {
        name: 'paramMapping',
        label: 'Маппинг параметров (что откуда берётся)',
        type: 'textarea',
        placeholder: 'query → из LLM\nuserId → из контекста сессии\nauthToken → из Keycloak',
      },
      {
        name: 'flowChecklist',
        label: 'Чек-лист AI Flow',
        type: 'checklist',
        options: [
          { value: 'scenario_created', label: 'Сценарий создан в AI Flow' },
          { value: 'mcp_tool_added', label: 'Компонент MCP Tool подключён с URL сервера' },
          { value: 'tools_discovered', label: 'AI Flow обнаружил инструменты (tools/list)' },
          { value: 'llm_connected', label: 'Вход/выход через LLM (AlfaLLM) настроены' },
          { value: 'params_mapped', label: 'Маппинг параметров настроен' },
          { value: 'relevant_test_ok', label: 'Релевантный запрос → правильный инструмент → корректные данные' },
          { value: 'irrelevant_test_ok', label: 'Нерелевантный запрос → инструмент не вызывается' },
          { value: 'invalid_test_ok', label: 'Невалидные данные → понятная ошибка' },
          { value: 'nlp_response_ok', label: 'AI формулирует ответ на естественном языке корректно' },
          { value: 'spotlight_notified', label: 'Команда Spotlight уведомлена: навык готов' },
          { value: 'spotlight_connected', label: 'Навык добавлен в маршрутизатор Spotlight' },
        ],
      },
    ],
  },
  {
    number: 6,
    title: 'E2E-тестирование и раскатка',
    subtitle: 'Совместное тестирование с командой Spotlight, поэтапный запуск',
    timeline: '2–5 дней',
    responsible: 'Разработчик + Команда Spotlight + PO',
    description: 'Проведите совместное E2E-тестирование полной цепочки в реальном UI Spotlight, убедитесь в отсутствии конфликтов и запланируйте поэтапную раскатку.',
    details: [
      '6.1. Совместное E2E-тестирование с командой Spotlight: полная цепочка от ввода клиента до ответа',
      '6.2. Проверить все согласованные сценарии в реальном UI Spotlight',
      '6.3. Проверить отсутствие конфликтов с другими навыками (корректная маршрутизация)',
      '6.4. Зафиксировать и устранить обнаруженные дефекты',
      '6.5. Определить аудиторию и график поэтапной раскатки',
    ],
    artifactName: 'Отчёт о тестировании и план раскатки',
    formFields: [
      {
        name: 'releaseDate',
        label: 'Планируемая дата релиза',
        type: 'date',
        required: true,
      },
      {
        name: 'audience',
        label: 'Аудитория раскатки',
        type: 'select',
        required: true,
        options: [
          { value: '1_percent', label: '1% пользователей' },
          { value: '5_percent', label: '5% пользователей' },
          { value: '25_percent', label: '25% пользователей' },
          { value: '50_percent', label: '50% пользователей' },
          { value: '100_percent', label: '100% пользователей' },
        ],
      },
      { name: 'testResults', label: 'Результаты E2E-тестирования', type: 'textarea', placeholder: 'Все 3 сценария прошли успешно...' },
      { name: 'bugs', label: 'Найденные и устранённые дефекты', type: 'textarea', placeholder: 'Список дефектов (если есть)' },
      {
        name: 'e2eChecklist',
        label: 'Чек-лист E2E',
        type: 'checklist',
        options: [
          { value: 'e2e_tested', label: 'Совместное E2E-тестирование проведено' },
          { value: 'all_scenarios_ok', label: 'Все сценарии проверены в реальном UI Spotlight' },
          { value: 'no_conflicts', label: 'Нет конфликтов с другими навыками' },
          { value: 'bugs_fixed', label: 'Дефекты зафиксированы и устранены' },
          { value: 'rollback_plan', label: 'План отката подготовлен' },
          { value: 'audience_defined', label: 'Аудитория и график раскатки определены' },
          { value: 'po_approved', label: 'PO подтвердил готовность к релизу' },
        ],
      },
    ],
  },
  {
    number: 7,
    title: 'Пост-релизный мониторинг',
    subtitle: 'Метрики, обратная связь, расширение',
    timeline: 'Постоянно',
    responsible: 'PO + Разработчик',
    description: 'Мониторьте метрики (обращения, конверсия, нагрузка на поддержку), собирайте обратную связь, планируйте расширение функционала.',
    details: [
      'Мониторить ответы, частотность запросов и метрики качества',
      'Собирать обратную связь от пользователей',
      'Отслеживать: количество обращений через Spotlight, конверсия в целевое действие, снижение нагрузки на поддержку',
      'Планировать расширение: добавление новых сценариев и инструментов в следующих спринтах',
    ],
    artifactName: 'Конфигурация мониторинга',
    formFields: [
      {
        name: 'metricsChecklist',
        label: 'Метрики для отслеживания',
        type: 'checklist',
        options: [
          { value: 'requests_count', label: 'Количество обращений через Spotlight' },
          { value: 'conversion', label: 'Конверсия в целевое действие' },
          { value: 'support_reduction', label: 'Снижение нагрузки на поддержку' },
          { value: 'user_satisfaction', label: 'Удовлетворённость пользователей' },
          { value: 'error_rate', label: 'Процент ошибок / некорректных ответов' },
          { value: 'response_time', label: 'Среднее время ответа' },
        ],
      },
      { name: 'feedbackChannel', label: 'Канал сбора обратной связи', type: 'text', placeholder: 'Jira / Slack / Email' },
      { name: 'expansionPlan', label: 'План расширения (новые сценарии)', type: 'textarea', placeholder: 'Какие новые сценарии планируете добавить в следующих спринтах?' },
    ],
  },
];

export const TOTAL_STEPS = ROADMAP_STEPS.length;
